-horizontal movement: horizontal borders -vertical movement: Return a ground variable, add weight while off ground else set vertical movement to 0
Error: still click continuously up & fall underneath the ground barrier.